### ISSUE TITLE
conda install fails

### ISSUE THREAD

**Issue by brian32768** [MarcSkovMadsen/awesome-panel#31]
**Describe the bug**
Following the instructions for conda, "conda install --file requirements_local.txt"" fails because there are
extra instructions in the requirements files like "-r ./requirements.txt". Presumably those are pip instructions.

The message is 
`CondaValueError: could not parse '-r ./requirements.txt' in: requirements_local.txt`

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by MarcSkovMadsen** [comment]
Hi @brian32768 

Thanks for reporting this. As you also notice the problem is a version of Python < 3.7.

I have updated the instructions in the README.md

![image](https://user-images.githubusercontent.com/42288570/103451722-b7c0c980-4cc7-11eb-8c46-02e3b7cdf324.png)

Let me know if there is something better I could do. Thanks.

**Comment by markqiu** [comment]
Describe the bug
Following the instructions for conda, "conda install --file requirements_local.txt"" fails because there are
extra instructions in the requirements files like "-r ./requirements.txt". Presumably those are pip instructions.

The message is
CondaValueError: could not parse '-r ./requirements.txt' in: requirements_local.txt

Desktop (please complete the following information):

OS: Windows 10
Python Version: 3.9
