### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by brian32768** [MarcSkovMadsen/awesome-panel#32]
**Describe the bug**
Since conda install failed I fall back on pip, which seems wrong since panel is part of Anaconda :-) Pip fails too :-(

**To Reproduce**
I set up the .venv and activated per instructions then did the install.
```bash
pip install -r requirements_local.txt -f https://download.pytorch.org/whl/torch_stable.html
Defaulting to user installation because normal site-packages is not writeable
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Obtaining file:///C:/Users/bwilson/source/repos/awesome-panel/package (from -r ./requirements.txt (l
ine 2))
Requirement already satisfied: wheel in c:\program files\arcgis\pro\bin\python\lib\site-packages (fr
om -r requirements_local.txt (line 7)) (0.36.2)
ERROR: Package 'awesome-panel' requires a different Python: 3.6.12 not in '>=3.7'
```
I know how to work around this (wrong version of Python) in conda, it's simple.
There is probably a similar way to fix venv too, maybe that should be in the instructions?

**Expected behaviour**
A working environment :-)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by MarcSkovMadsen** [comment]
Hi @brian32768 

Thanks for reporting this. As you also notice the problem is a version of Python < 3.7.

I have updated the instructions in the README.md

![image](https://user-images.githubusercontent.com/42288570/103451722-b7c0c980-4cc7-11eb-8c46-02e3b7cdf324.png)

Let me know if there is something better I could do. Thanks.
